"use client";
import { useEffect,useMemo,useState } from "react";
import { addDoc, collection, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc, where } from "firebase/firestore";
import { Atom, BookOpen, CalendarDays, CircleDollarSign, ClipboardCheck, FileText, LogOut, Megaphone, Plus, Search, Sparkles, Users, X } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import { menuItems } from "@/components/icons";
import { useToast } from "@/components/toast";
import { db, firebaseConfigured, missingFirebaseEnv, workspaceId } from "@/lib/firebase";

type DataRow=Record<string,unknown>&{id:string};
const previews:Record<string,DataRow[]>={
 meetings:[{id:"m1",title:"첫 모임을 만들어 활동을 시작해 보세요",month:3,round:1,startsAt:"일정 미정",place:"장소 미정",status:"예정"}],
 lessons:[],growth:[],lectures:[],purchases:[],resources:[],booklet:[],notices:[]
};
const meta:Record<string,{title:string;desc:string;button:string;collection:string}>={
 meetings:{title:"월별 모임",desc:"우리의 만남과 수업 나눔 과정을 시간순으로 기록합니다.",button:"새 모임",collection:"meetings"},
 lessons:{title:"수업 사례",desc:"수업의 고민과 발견을 차곡차곡 나누어 보세요.",button:"사례 작성",collection:"lessonCases"},
 growth:{title:"개인 성장 기록",desc:"매월의 배움이 나의 변화로 이어지는 과정을 기록합니다.",button:"성장 기록",collection:"reflections"},
 lectures:{title:"강의·연수",desc:"강의 자료와 참여자들의 배움을 한곳에 모읍니다.",button:"강의 기록",collection:"lectures"},
 purchases:{title:"도서·물품",desc:"구매 요청부터 예산 집행과 활용 후기까지 투명하게 관리합니다.",button:"구매 요청",collection:"purchaseRequests"},
 resources:{title:"자료실",desc:"수업 활동지, 발표 자료, 사진과 링크를 빠르게 찾아보세요.",button:"자료 등록",collection:"resources"},
 booklet:{title:"자료집 제작",desc:"한 해의 기록을 고르고 다듬어 공동 자료집으로 엮습니다.",button:"원고 제출",collection:"bookletEntries"},
 notices:{title:"공지사항",desc:"모임 일정과 준비물, 작성 마감 소식을 확인합니다.",button:"공지 작성",collection:"announcements"},
 admin:{title:"관리자 설정",desc:"운영 연도, 구성원 승인, 예산과 사이트 구성을 관리합니다.",button:"새 운영 연도",collection:"years"}
};

export default function Page(){
 const {profile,loading,demo,login,logout,enterDemo}=useAuth(); const toast=useToast();
 const [active,setActive]=useState("home"),[rows,setRows]=useState<DataRow[]>([]),[modal,setModal]=useState(false),[saving,setSaving]=useState(false),[queryText,setQueryText]=useState("");
 useEffect(()=>{if(active==="home"||!profile||demo||!db){setRows(previews[active]||[]);return}const col=meta[active]?.collection;if(!col)return;const q=query(collection(db,col),where("workspaceId","==",profile.workspaceId),where("yearId","==","2026"),where("isDeleted","==",false),orderBy("updatedAt","desc"));return onSnapshot(q,s=>setRows(s.docs.map(d=>({id:d.id,...d.data()}))),()=>toast("목록을 불러오지 못했습니다. 인덱스를 확인해 주세요.","error"))},[active,profile,demo,toast]);
 const visible=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(queryText.toLowerCase())),[rows,queryText]);
 if(loading)return <div className="pending"><div><Atom size={44}/><h2>기록실을 준비하고 있습니다</h2></div></div>;
 if(!profile)return <LoginScreen login={login} enterDemo={enterDemo} toast={toast}/>;
 if(profile.approvalStatus!=="approved")return <div className="pending"><div className="mark" style={{margin:"auto"}}><ClipboardCheck/></div><h1>관리자의 승인을 기다리고 있습니다</h1><p className="muted">가입 요청이 전달되었습니다. 승인 후 모든 기록 공간을 이용할 수 있어요.</p><button className="secondary" onClick={logout}>로그아웃</button></div>;
 const select=(id:string)=>{setActive(id);setQueryText("")};
 return <div className="shell"><aside className="sidebar"><Brand/><nav>{menuItems.filter(i=>!i.admin||profile.role==="admin").map(i=><button key={i.id} className={`nav-btn ${active===i.id?"active":""}`} onClick={()=>select(i.id)}><i.icon size={19}/>{i.label}</button>)}</nav><div className="profile"><strong>{profile.displayName}</strong><div className="muted">{profile.role==="admin"?"관리자":"분임원"}</div><button aria-label="로그아웃" onClick={logout} style={{position:"absolute",right:10,top:17,border:0,background:"none"}}><LogOut size={17}/></button></div></aside><main className="content"><header className="topbar"><div><span className="muted">동부 수업평가나눔교사단</span><h1>{active==="home"?"우리의 수업 연구 노트":meta[active]?.title}</h1></div><select className="year" aria-label="운영 연도"><option>2026년</option></select></header>{active==="home"?<Dashboard name={profile.displayName}/>:active==="admin"?<AdminPanel demo={demo}/>:<Section id={active} rows={visible} queryText={queryText} setQueryText={setQueryText} open={()=>setModal(true)} isAdmin={profile.role==="admin"}/>}</main><Mobile active={active} select={select}/>{modal&&<CreateModal section={active} close={()=>setModal(false)} saving={saving} save={async data=>{setSaving(true);try{if(demo||!db){setRows(v=>[{id:crypto.randomUUID(),...data,status:"임시 저장"},...v]);toast("미리보기 기록을 저장했습니다.");}else{await addDoc(collection(db,meta[active].collection),{...data,workspaceId,yearId:"2026",authorId:profile.uid,authorName:profile.displayName,status:active==="purchases"?"구매 요청":"임시 저장",createdAt:serverTimestamp(),updatedAt:serverTimestamp(),isDeleted:false});toast("안전하게 저장했습니다.")}setModal(false)}catch(e){toast(e instanceof Error?e.message:"저장하지 못했습니다.","error")}finally{setSaving(false)}}}/>}</div>
}
function LoginScreen({login,enterDemo,toast}:{login:(name:string,password:string,register?:boolean)=>Promise<void>;enterDemo:()=>void;toast:(message:string,type?:"ok"|"error")=>void}){const [name,setName]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[register,setRegister]=useState(false);const submit=async()=>{setBusy(true);try{await login(name,password,register)}catch(error){const code=(error as {code?:string}).code;toast(code==="auth/invalid-credential"?"이름 또는 비밀번호를 확인해 주세요.":code==="auth/email-already-in-use"?"이미 가입된 이름입니다. 로그인해 주세요.":error instanceof Error?error.message:"로그인하지 못했습니다.","error")}finally{setBusy(false)}};return <main className="login"><section className="hero"><h1>동부 수업평가나눔교사단 과학분임</h1></section><section className="login-panel"><form className="login-card" onSubmit={e=>{e.preventDefault();submit()}}><div className="mark"><Atom/></div><h2>{register?"분임원 가입":"기록실 로그인"}</h2><p>이름과 비밀번호로 로그인합니다. 처음 가입한 분임원은 관리자 승인 후 이용할 수 있습니다.</p>{!firebaseConfigured&&<div className="config-warning" role="alert"><strong>Firebase 연결 설정이 필요합니다.</strong><span>Vercel 환경 변수에서 누락: {missingFirebaseEnv.join(", ")}</span></div>}<label className="login-field">이름<input value={name} onChange={e=>setName(e.target.value)} autoComplete="username" placeholder="이름을 입력하세요" required/></label><label className="login-field">비밀번호<input value={password} onChange={e=>setPassword(e.target.value)} type="password" inputMode="numeric" autoComplete={register?"new-password":"current-password"} placeholder="초기 비밀번호 0000" required/></label><button className="primary wide" disabled={busy||!firebaseConfigured}>{busy?"확인 중…":register?"가입 요청하기":"로그인"}</button>{!register&&<button type="button" className="admin-login" onClick={()=>{setName("성소연");setPassword("");}}>관리자 로그인</button>}<button type="button" className="demo" onClick={()=>setRegister(value=>!value)}>{register?"이미 가입했어요 · 로그인":"처음 오셨나요? 가입 요청"}</button>{!firebaseConfigured&&<button type="button" className="demo" onClick={enterDemo}>설정 전 화면 미리보기</button>}</form></section></main>}
function Brand(){return <div className="brand"><div className="mark"><Atom size={23}/></div><div><strong>과학 수업나눔</strong><small>기록실</small></div></div>}
function Dashboard({name}:{name:string}){return <><section className="welcome"><div><span className="badge">2026 운영 중</span><h2>{name} 선생님, 오늘도 반갑습니다.</h2><p>우리의 작은 기록이 더 나은 과학 수업을 만듭니다.</p></div><Sparkles size={44} color="#55a99a"/></section><section className="stats"><Stat icon={<CalendarDays/>} label="올해 모임" value="0회"/><Stat icon={<BookOpen/>} label="수업 사례" value="0건"/><Stat icon={<Users/>} label="강의·연수" value="0건"/><Stat icon={<CircleDollarSign/>} label="남은 예산" value="₩0"/></section><div className="grid2"><section className="card"><div className="section-title"><h2>다가오는 모임</h2><span className="badge">예정</span></div><div className="meeting"><div className="datebox"><small>MAR</small><b>—</b></div><div><strong>첫 모임 일정을 등록해 주세요</strong><p className="muted">날짜와 장소, 함께 나눌 주제를 정해 보세요.</p></div></div></section><section className="card"><div className="section-title"><h2>나의 작성 현황</h2><span className="muted">이번 달</span></div><Check label="수업 사례" done={false}/><Check label="개인 성찰" done={false}/><Check label="자료집 원고" done={false}/></section><section className="card"><div className="section-title"><h2>최근 등록된 자료</h2></div><div className="empty"><FileText size={30}/><p>아직 등록된 자료가 없습니다.<br/>첫 자료를 나누어 주세요.</p></div></section><section className="card"><div className="section-title"><h2>최근 공지사항</h2></div><div className="empty"><Megaphone size={30}/><p>새로운 공지가 여기에 표시됩니다.</p></div></section></div></>}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="card stat"><span>{icon} {label}</span><strong>{value}</strong></div>};
function Check({label,done}:{label:string;done:boolean}){return <div style={{margin:"16px 0"}}><div style={{display:"flex",justifyContent:"space-between"}}><span>{label}</span><span className={`badge ${done?"":"warn"}`}>{done?"작성 완료":"천천히 작성해 보세요"}</span></div><div className="progress"><i style={{width:done?"100%":"12%"}}/></div></div>}
function Section({id,rows,queryText,setQueryText,open,isAdmin}:{id:string;rows:DataRow[];queryText:string;setQueryText:(s:string)=>void;open:()=>void;isAdmin:boolean}){const m=meta[id];const allowed=id!=="notices"&&id!=="admin"||isAdmin;return <><div className="page-head"><div><h2>{m.title}</h2><p className="muted">{m.desc}</p></div>{allowed&&<button className="primary" onClick={open}><Plus size={17} style={{display:"inline"}}/> {m.button}</button>}</div><div className="filters"><label className="field"><Search size={16} style={{display:"inline",marginRight:8}}/><input value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder="검색어 입력" style={{border:0,outline:0}}/></label><select className="field"><option>전체 상태</option><option>임시 저장</option><option>완료</option></select></div>{rows.length?<div className="cards">{rows.map(row=><article className="card item" key={row.id}><span className="badge">{String(row.status||"임시 저장")}</span><h3>{String(row.title||row.itemName||"제목 없는 기록")}</h3><p className="muted">{String(row.summary||row.purpose||"기록을 열어 자세한 내용을 확인하세요.")}</p><footer>{String(row.authorName||"작성자 정보 자동 저장")} · 2026</footer></article>)}</div>:<div className="card empty"><Sparkles size={34}/><h3>아직 기록이 없습니다</h3><p>첫 기록을 남기면 이곳에 차곡차곡 쌓입니다.</p>{allowed&&<button className="secondary" onClick={open}>{m.button}</button>}</div>}</>}
function Mobile({active,select}:{active:string;select:(id:string)=>void}){const ids=["home","meetings","lessons","resources","notices"];return <nav className="mobile-nav">{menuItems.filter(i=>ids.includes(i.id)).map(i=><button key={i.id} className={active===i.id?"active":""} onClick={()=>select(i.id)}><i.icon size={20}/>{i.label}</button>)}</nav>}
function AdminPanel({demo}:{demo:boolean}){
 const [users,setUsers]=useState<DataRow[]>([]);const toast=useToast();
 useEffect(()=>{
  if(demo||!db)return;
  const usersQuery=query(collection(db,"users"),where("workspaceId","==",workspaceId));
  return onSnapshot(usersQuery,snapshot=>{setUsers(snapshot.docs.map(item=>({id:item.id,...item.data()})));});
 },[demo]);
 const approve=async(id:string)=>{if(!db)return;await updateDoc(doc(db,"users",id),{approvalStatus:"approved",updatedAt:serverTimestamp()});toast("분임원 가입을 승인했습니다.")};
 return <><div className="page-head"><div><h2>관리자 설정</h2><p className="muted">사용자 승인과 운영 환경을 안전하게 관리합니다.</p></div></div><div className="grid2"><section className="card"><div className="section-title"><h2>가입 승인</h2><span className="badge warn">{users.filter(u=>u.approvalStatus==="pending").length}명 대기</span></div>{demo?<div className="empty">Firebase 연결 후 실제 가입 요청이 표시됩니다.</div>:users.filter(u=>u.approvalStatus==="pending").map(u=><div className="meeting" key={u.id}><div style={{flex:1}}><strong>{String(u.displayName)}</strong><div className="muted">{String(u.email)}</div></div><button className="primary" onClick={()=>approve(u.id).catch(()=>toast("승인에 실패했습니다.","error"))}>승인</button></div>)}</section><section className="card"><div className="section-title"><h2>운영 설정</h2></div><label>활성 연도<select className="field wide"><option>2026년</option></select></label><label>연간 예산<input className="field wide" inputMode="numeric" placeholder="₩ 0"/></label><button className="primary wide" onClick={()=>toast("운영 설정을 저장했습니다.")}>설정 저장</button></section></div></>;
}
function CreateModal({section,close,save,saving}:{section:string;close:()=>void;save:(d:Record<string,unknown>)=>void;saving:boolean}){const [title,setTitle]=useState(""),[summary,setSummary]=useState("");const isPurchase=section==="purchases";return <div className="modal-back" onMouseDown={e=>{if(e.target===e.currentTarget&&confirm("작성 중인 내용이 사라집니다. 닫을까요?"))close()}}><form className="modal" onSubmit={e=>{e.preventDefault();if(!title.trim())return;save(isPurchase?{itemName:title,purpose:summary,category:"도서",quantity:1,unitPrice:0}:{title,summary})}}><button type="button" aria-label="닫기" onClick={close} style={{float:"right",border:0,background:"none"}}><X/></button><h2>{meta[section]?.button}</h2><p className="muted">작성자와 생성·수정 시각은 자동으로 저장됩니다.</p><div className="form-grid"><label className="full">{isPurchase?"품목명":"제목"}<input className="field" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="기록의 제목을 입력하세요"/></label><label>상태<select className="field"><option>임시 저장</option><option>작성 완료</option></select></label><label>공개 범위<select className="field"><option>분임원 전체 공개</option><option>나와 관리자만</option></select></label><label className="full">{isPurchase?"구매 목적":"내용"}<textarea className="field" rows={8} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="생각과 맥락을 자세히 기록해 주세요."/></label></div><div className="form-actions"><button type="button" className="secondary" onClick={close}>취소</button><button className="primary" disabled={saving}>{saving?"저장 중…":"임시 저장"}</button></div></form></div>}
